"""first migration for the project

Revision ID: 877243570c44
Revises: 
Create Date: 2022-08-15 14:44:47.798514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877243570c44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('admin', 'base_user', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('suggester',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('admin', 'base_user', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('suggestion',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance_rate', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='state'), nullable=False),
    sa.Column('suggester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suggester_id'], ['suggester.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    op.drop_table('suggester')
    op.drop_table('administrator')
    # ### end Alembic commands ###
