"""added certification to the suggestion table

Revision ID: f5aaa2ba68e4
Revises: 5b36a7139547
Create Date: 2022-08-18 12:36:03.898706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5aaa2ba68e4"
down_revision = "5b36a7139547"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "suggestion",
        sa.Column("course_certificate_url", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suggestion", "course_certificate_url")
    # ### end Alembic commands ###
